# Generated by Django 3.2.8 on 2021-12-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_date',
            new_name='question_text',
        ),
    ]
